version: '3.8'

volumes:
  postgres_vol:
    driver: local

networks:
  correct_net:
    driver: bridge

services:
  api:
    image: jserenarruda/syscorrect:v2
    ports: 
      - 3333:3333
    networks:
      - correct_net
    depends_on:
      - postgresdb
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgresdb:5432/correct-db?schema=public
      SECRET_KEY_TOKEN_ADMIN: correct_admin_token
      SECRET_KEY_TOKEN_COMPANY_ADMIN: company_admin_token
      SECRET_KEY_TOKEN_APP_USER: app_user_token
      SECRET_KEY_TOKEN_COMPANY_SECONDARY_USER: company_user_token
    command: sh -c "npx prisma migrate dev && npm run dev"

  postgresdb:
    image: postgres:13.4
    ports:
      - 5432:5432
    networks:
      - correct_net
    volumes:
      - postgres_vol:/var/lib/postgresql/data  # Mapeamento para o diretório de dados do PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: correct-db
